const DB='PersonalLifePlannerDB', VER=1;
let db, state={tab:'today', date:isoDate(new Date()), selectedDate:isoDate(new Date()), month:new Date(new Date().getFullYear(),new Date().getMonth(),1)};
const $=s=>document.querySelector(s);
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function isoDate(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function fmtDate(s){return new Intl.DateTimeFormat('fa-IR',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date(s+'T12:00:00'))}
function fmtNum(n){return new Intl.NumberFormat('fa-IR').format(Number(n)||0)}
function money(n,c='تومان'){return fmtNum(n)+' '+c}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{db=r.result;
['days','tasks','habits','habitLogs','events','people','journal','categories','sources','transactions'].forEach(n=>{if(!db.objectStoreNames.contains(n)){let k=db.createObjectStore(n,{keyPath:'id'});if(n==='events'||n==='journal'||n==='transactions'||n==='tasks'||n==='habitLogs')k.createIndex('date','date');if(n==='habitLogs')k.createIndex('habitId','habitId')}});
};r.onsuccess=()=>res(db);r.onerror=()=>rej(r.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function all(store){return new Promise((res,rej)=>{let r=tx(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(store,obj){return new Promise((res,rej)=>{let r=tx(store,'readwrite').put(obj);r.onsuccess=()=>res(obj);r.onerror=()=>rej(r.error)})}
function del(store,id){return new Promise((res,rej)=>{let r=tx(store,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function seed(){if((await all('categories')).length===0)for(const n of ['Food','Groceries','Transportation','Bills','Health','Entertainment','Shopping','Work','Banking Fees','Travel','Education','Other'])await put('categories',{id:uid(),name:n,createdAt:Date.now()});if((await all('sources')).length===0)for(const n of ['Cash','Mellat','Saman','Pasargad'])await put('sources',{id:uid(),name:n,createdAt:Date.now()})}
function nav(){return `<div class="tabs"><div class="tabs-inner">
<button class="tab ${state.tab==='today'?'active':''}" onclick="go('today')"><span>⌂</span>Today</button>
<button class="tab ${state.tab==='calendar'?'active':''}" onclick="go('calendar')"><span>▦</span>Calendar</button>
<button class="tab" onclick="quickAdd()"><span>＋</span>Add</button>
<button class="tab ${state.tab==='search'?'active':''}" onclick="go('search')"><span>⌕</span>Search</button>
<button class="tab ${state.tab==='insights'?'active':''}" onclick="go('insights')"><span>◒</span>Insights</button></div></div>`}
async function render(){let main='';if(state.tab==='today')main=await today();if(state.tab==='calendar')main=await calendar();if(state.tab==='search')main=await search();if(state.tab==='insights')main=await insights();$('#app').innerHTML=main+nav();if(state.tab==='today')bindToday();if(state.tab==='search'){$('#q').focus();$('#q').addEventListener('input',renderSearchResults)}} 
function header(title,sub){return `<header class="top"><div class="toprow"><div><div class="title">${title}</div><div class="subtitle">${sub}</div></div><button class="iconbtn" onclick="settings()">⚙️</button></div></header>`}
async function today(){const d=state.date;let tasks=(await all('tasks')).filter(x=>x.dueDate===d&&!x.completed).sort((a,b)=>(a.priority||9)-(b.priority||9));let habits=await all('habits'),logs=await all('habitLogs');let events=(await all('events')).filter(x=>x.date===d).sort((a,b)=>(a.startTime||'').localeCompare(b.startTime||''));let tr=(await all('transactions')).filter(x=>x.date===d);let journals=(await all('journal')).filter(x=>x.date===d).sort((a,b)=>b.createdAt-a.createdAt);let day=(await all('days')).find(x=>x.date===d);return `${header('امروز',fmtDate(d))}<main>
<div class="card"><div class="sectionhead"><div class="sectiontitle">حال امروز</div></div><div class="mood">${[['😄','عالی'],['🙂','خوب'],['😐','معمولی'],['😔','بد'],['😫','خیلی بد']].map(([e,l])=>`<button class="${day?.mood===e?'active':''}" onclick="setMood('${e}')">${e}<label>${l}</label></button>`).join('')}</div></div>
<div class="card"><div class="sectionhead"><div class="sectiontitle">اولویت‌های امروز</div><button class="pill" onclick="quickAdd('task')">+ افزودن</button></div>${tasks.length?tasks.map(t=>`<div class="item row"><button class="check" onclick="completeTask('${t.id}')"></button><div style="flex:1"><b>${esc(t.title)}</b><div class="small">${t.priority<=2?'مهم':''}</div></div></div>`).join(''):'<div class="empty">امروز کاری ثبت نشده. ۳ اولویت اصلی‌ات را اضافه کن.</div>'}</div>
<div class="card"><div class="sectionhead"><div class="sectiontitle">عادت‌ها</div><button class="pill" onclick="quickAdd('habit')">مدیریت</button></div>${habits.length?habits.map(h=>{let done=logs.some(l=>l.habitId===h.id&&l.date===d&&l.completed);return `<div class="item row"><button class="check ${done?'done':''}" onclick="toggleHabit('${h.id}',${done})">${done?'✓':''}</button><div style="flex:1"><b>${esc(h.name)}</b></div><span class="small">${h.frequency||'روزانه'}</span></div>`}).join(''):'<div class="empty">هنوز عادتی نداری.</div>'}</div>
<div class="card"><div class="sectionhead"><div class="sectiontitle">رویدادها</div><button class="pill" onclick="quickAdd('event')">+ افزودن</button></div>${events.length?events.map(e=>`<div class="item"><div class="row between"><b>${esc(e.title)}</b><span class="small">${e.startTime||''}</span></div><div class="small">${esc(e.location||'')}${e.location?' · ':''}${esc(e.peopleText||'')}</div></div>`).join(''):'<div class="empty">رویدادی برای امروز نیست.</div>'}</div>
<div class="card"><div class="sectionhead"><div class="sectiontitle">هزینه‌ها</div><button class="pill" onclick="quickAdd('expense')">+ افزودن</button></div>${tr.filter(x=>x.type==='expense'||x.type==='fee').length?tr.filter(x=>x.type==='expense'||x.type==='fee').map(x=>`<div class="item row between"><div><b>${esc(x.categoryName||x.type)}</b><div class="small">${esc(x.sourceName||'')} · ${esc(x.note||'')}</div></div><span class="amount">${money(x.amount,x.currency)}</span></div>`).join(''):'<div class="empty">امروز هزینه‌ای ثبت نشده.</div>'}</div>
<div class="card"><div class="sectionhead"><div class="sectiontitle">ژورنال</div><button class="pill" onclick="quickAdd('journal')">نوشتن</button></div>${journals.length?journals.slice(0,2).map(j=>`<div class="item"><div>${esc(j.text).slice(0,180)}</div><div class="small">${new Date(j.createdAt).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})}</div></div>`).join(''):'<div class="empty">ذهن‌ات را خالی کن؛ هر چیزی را که می‌خواهی بنویس.</div>'}</div>
<button class="secondary" style="width:100%" onclick="openDay('${d}')">مشاهده Timeline کامل روز →</button>
</main><button class="fab" onclick="quickAdd()">＋</button>`}
function bindToday(){}
async function setMood(m){let days=await all('days'),d=days.find(x=>x.date===state.date)||{id:uid(),date:state.date,createdAt:Date.now()};d.mood=m;d.updatedAt=Date.now();await put('days',d);render()}
async function completeTask(id){let a=await all('tasks'),t=a.find(x=>x.id===id);if(t){t.completed=true;t.completedAt=Date.now();await put('tasks',t);render()}}
async function toggleHabit(id,done){let ls=await all('habitLogs');let l=ls.find(x=>x.habitId===id&&x.date===state.date);if(done&&l)await del('habitLogs',l.id);else await put('habitLogs',l||{id:uid(),habitId:id,date:state.date,completed:true,createdAt:Date.now()});render()}
async function calendar(){let m=state.month,y=m.getFullYear(),mo=m.getMonth(),first=new Date(y,mo,1),last=new Date(y,mo+1,0),offset=(first.getDay()+1)%7;let days=[];for(let i=0;i<offset;i++)days.push('<div class="day"></div>');let ev=await all('events'),jr=await all('journal'),tr=await all('transactions'),hl=await all('habitLogs');for(let n=1;n<=last.getDate();n++){let d=isoDate(new Date(y,mo,n)),has=ev.some(x=>x.date===d)||jr.some(x=>x.date===d)||tr.some(x=>x.date===d)||hl.some(x=>x.date===d);days.push(`<button class="day ${d===isoDate(new Date())?'today':''} ${d===state.selectedDate?'selected':''}" onclick="openDay('${d}')">${n}${has?'<i class="dot"></i>':''}</button>`)}return `${header('تقویم','هر روزی که اطلاعات داشته باشد با نقطه مشخص می‌شود')}<main><div class="card"><div class="calendar-head"><button class="iconbtn" onclick="prevMonth()">‹</button><b>${new Intl.DateTimeFormat('fa-IR',{month:'long',year:'numeric'}).format(m)}</b><button class="iconbtn" onclick="nextMonth()">›</button></div><div class="cal">${['ش','ی','د','س','چ','پ','ج'].map(x=>`<div class="dow">${x}</div>`).join('')}${days.join('')}</div></div><div class="card"><b>نمایش روز</b><div class="small" style="margin-top:6px">${fmtDate(state.selectedDate)}</div><button class="primary" style="margin-top:12px;width:100%" onclick="openDay('${state.selectedDate}')">باز کردن Timeline</button></div></main>`}
function prevMonth(){state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);render()}function nextMonth(){state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);render()}
async function openDay(d){state.selectedDate=d;let items=[];let events=(await all('events')).filter(x=>x.date===d),tr=(await all('transactions')).filter(x=>x.date===d),jr=(await all('journal')).filter(x=>x.date===d),tasks=(await all('tasks')).filter(x=>x.dueDate===d),hl=(await all('habitLogs')).filter(x=>x.date===d&&x.completed),hab=await all('habits');events.forEach(x=>items.push({time:x.startTime||'23:59',html:`<div class="eventtype">رویداد · ${esc(x.eventType||'Personal')}</div><div class="eventtitle">${esc(x.title)}</div><div class="small">${esc(x.location||'')} ${esc(x.peopleText||'')}</div>`}));tr.forEach(x=>items.push({time:x.time||'23:59',html:`<div class="eventtype">${x.type==='income'?'درآمد':x.type==='fee'?'کارمزد':'هزینه'}</div><div class="eventtitle">${money(x.amount,x.currency)}</div><div class="small">${esc(x.categoryName||'')} · ${esc(x.sourceName||'')}</div>`}));jr.forEach(x=>items.push({time:x.time||'23:59',html:`<div class="eventtype">ژورنال</div><div class="eventtitle">${esc(x.text).slice(0,240)}</div>`}));tasks.filter(x=>x.completed).forEach(x=>items.push({time:'00:00',html:`<div class="eventtype">کار انجام‌شده</div><div class="eventtitle">✓ ${esc(x.title)}</div>`}));for(const l of hl){let h=hab.find(x=>x.id===l.habitId);if(h)items.push({time:'00:00',html:`<div class="eventtype">عادت</div><div class="eventtitle">✓ ${esc(h.name)}</div>`})}items.sort((a,b)=>a.time.localeCompare(b.time));$('#app').innerHTML=`${header(fmtDate(d),'Timeline روز')}<main><div class="card"><div class="timeline">${items.length?items.map(x=>`<div class="eventline"><div class="small">${x.time}</div>${x.html}</div>`).join(''):'<div class="empty">این روز هنوز اطلاعاتی ندارد.</div>'}</div></div><button class="secondary" style="width:100%" onclick="go('calendar')">← بازگشت به تقویم</button></main>${nav()}`}
async function search(){return `${header('جستجو','تاریخ، شخص، بانک، دسته یا متن را پیدا کن')}<main><div class="card searchbar"><span>⌕</span><input id="q" placeholder="مثلاً Ali، Restaurant، 2026-09-07..." autocomplete="off"></div><div id="results"></div></main>`}
async function renderSearchResults(){let q=$('#q').value.trim().toLowerCase();if(!q){$('#results').innerHTML='<div class="empty">برای شروع جستجو کن.</div>';return}let [ev,jr,tr,ta,pe,ha]=await Promise.all([all('events'),all('journal'),all('transactions'),all('tasks'),all('people'),all('habits')]);let out=[];for(const x of ev)if(JSON.stringify(x).toLowerCase().includes(q))out.push(`📅 <b>${esc(x.title)}</b><div class="small">${x.date} · Event</div>`);for(const x of jr)if(JSON.stringify(x).toLowerCase().includes(q))out.push(`✍️ <b>${esc(x.text).slice(0,120)}</b><div class="small">${x.date} · Journal</div>`);for(const x of tr)if(JSON.stringify(x).toLowerCase().includes(q))out.push(`💰 <b>${money(x.amount,x.currency)}</b><div class="small">${x.date} · ${esc(x.categoryName||x.type)} · ${esc(x.sourceName||'')}</div>`);for(const x of ta)if(JSON.stringify(x).toLowerCase().includes(q))out.push(`□ <b>${esc(x.title)}</b><div class="small">${x.dueDate} · Task</div>`);for(const x of pe)if(JSON.stringify(x).toLowerCase().includes(q))out.push(`👤 <b>${esc(x.name)}</b><div class="small">Person</div>`);for(const x of ha)if(JSON.stringify(x).toLowerCase().includes(q))out.push(`✓ <b>${esc(x.name)}</b><div class="small">Habit</div>`);$('#results').innerHTML=`<div class="card">${out.length?out.map(x=>`<div class="item">${x}</div>`).join(''):`<div class="empty">نتیجه‌ای پیدا نشد.</div>`}</div>`}
async function insights(){let tr=await all('transactions'),exp=tr.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.amount),0),inc=tr.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.amount),0),fees=tr.filter(x=>x.type==='fee').reduce((s,x)=>s+Number(x.amount),0);let cats={};tr.filter(x=>x.type==='expense').forEach(x=>cats[x.categoryName||'Other']=(cats[x.categoryName||'Other']||0)+Number(x.amount));let top=Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,5);let h=await all('habits'),logs=await all('habitLogs');return `${header('Insights','یک نگاه سریع به زندگی ثبت‌شده‌ات')}<main><div class="grid2"><div class="metric">هزینه‌ها<b>${fmtNum(exp)}</b></div><div class="metric">درآمد<b>${fmtNum(inc)}</b></div><div class="metric">کارمزد<b>${fmtNum(fees)}</b></div><div class="metric">خالص جریان نقدی<b>${fmtNum(inc-exp-fees)}</b></div></div><div class="card"><div class="sectiontitle">بیشترین دسته‌های هزینه</div>${top.length?top.map(([n,v])=>`<div class="item row between"><span>${esc(n)}</span><b>${fmtNum(v)}</b></div>`).join(''):'<div class="empty">هنوز داده مالی کافی نیست.</div>'}</div><div class="card"><div class="sectiontitle">عادت‌ها</div><div class="item row between"><span>تعداد عادت‌ها</span><b>${fmtNum(h.length)}</b></div><div class="item row between"><span>کل تیک‌های ثبت‌شده</span><b>${fmtNum(logs.filter(x=>x.completed).length)}</b></div></div><div class="card"><div class="sectiontitle">پشتیبان‌گیری</div><p class="small">برای جلوگیری از از دست رفتن آرشیو، هر چند وقت یک‌بار Export بگیر.</p><div class="row"><button class="primary" style="flex:1" onclick="exportData()">Export</button><button class="secondary" style="flex:1" onclick="document.querySelector('#importFile').click()">Import</button></div><input id="importFile" type="file" accept=".json" style="display:none" onchange="importData(event)"></div></main>`}
async function quickAdd(type){type=type||'';if(!type){show(`<h2>ثبت سریع</h2><div class="actions">${[['expense','💰','هزینه'],['habit','✓','عادت'],['event','📅','رویداد'],['journal','✍️','ژورنال'],['task','□','کار']].map(a=>`<button class="action" onclick="quickAdd('${a[0]}')"><b>${a[1]}</b>${a[2]}</button>`).join('')}</div>`);return}if(type==='expense')return expenseForm();if(type==='habit')return habitForm();if(type==='event')return eventForm();if(type==='journal')return journalForm();if(type==='task')return taskForm()}
async function expenseForm(){let cats=await all('categories'),src=await all('sources');show(`<h2>ثبت هزینه</h2><div class="formgrid"><input id="amt" type="number" inputmode="decimal" placeholder="مبلغ" autofocus><select id="cat">${cats.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select><select id="src">${src.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select><input id="note" placeholder="یادداشت (اختیاری)"><button class="primary" onclick="saveExpense()">ذخیره</button></div>`)}
async function saveExpense(){let cats=await all('categories'),src=await all('sources');let c=cats.find(x=>x.id===$('#cat').value),s=src.find(x=>x.id===$('#src').value);let now=new Date();await put('transactions',{id:uid(),amount:Number($('#amt').value),currency:'تومان',date:state.date,time:now.toTimeString().slice(0,5),categoryId:c?.id,categoryName:c?.name,sourceId:s?.id,sourceName:s?.name,type:'expense',note:$('#note').value,createdAt:Date.now()});close();toast('هزینه ذخیره شد');render()}
async function habitForm(){show(`<h2>عادت جدید</h2><div class="formgrid"><input id="hn" placeholder="مثلاً ورزش" autofocus><select id="hf"><option>روزانه</option><option>شنبه، دوشنبه، چهارشنبه</option><option>۳ بار در هفته</option></select><button class="primary" onclick="saveHabit()">ساخت عادت</button></div>`)}
async function saveHabit(){await put('habits',{id:uid(),name:$('#hn').value.trim(),frequency:$('#hf').value,startDate:state.date,createdAt:Date.now()});close();toast('عادت ساخته شد');render()}
async function eventForm(){show(`<h2>رویداد</h2><div class="formgrid"><input id="et" placeholder="عنوان رویداد" autofocus><input id="ed" type="date" value="${state.date}"><div class="grid2"><input id="es" type="time"><input id="ee" type="time"></div><input id="el" placeholder="مکان (اختیاری)"><input id="ep" placeholder="افراد (مثلاً Ali, Sara)"><textarea id="en" placeholder="یادداشت (اختیاری)"></textarea><button class="primary" onclick="saveEvent()">ذخیره</button></div>`)}
async function saveEvent(){await put('events',{id:uid(),title:$('#et').value.trim(),date:$('#ed').value,startTime:$('#es').value,endTime:$('#ee').value,location:$('#el').value,peopleText:$('#ep').value,eventType:'Personal',note:$('#en').value,createdAt:Date.now()});close();toast('رویداد ذخیره شد');render()}
async function journalForm(){show(`<h2>ژورنال</h2><div class="formgrid"><textarea id="jt" placeholder="هر چیزی که در ذهن داری..." autofocus></textarea><input id="jtags" placeholder="#idea #memory #work"><button class="primary" onclick="saveJournal()">ذخیره</button></div>`)}
async function saveJournal(){await put('journal',{id:uid(),text:$('#jt').value.trim(),date:state.date,time:new Date().toTimeString().slice(0,5),tags:$('#jtags').value,createdAt:Date.now()});close();toast('نوشته ذخیره شد');render()}
async function taskForm(){let tasks=(await all('tasks')).filter(x=>x.dueDate===state.date);if(tasks.length>=6){toast('حداکثر ۶ کار روزانه');return}show(`<h2>اولویت امروز</h2><div class="formgrid"><input id="tt" placeholder="مثلاً تکمیل پروژه" autofocus><select id="tp"><option value="1">اولویت ۱</option><option value="2">اولویت ۲</option><option value="3" selected>اولویت ۳</option><option value="4">بعدی</option></select><button class="primary" onclick="saveTask()">ذخیره</button></div>`)}
async function saveTask(){await put('tasks',{id:uid(),title:$('#tt').value.trim(),priority:Number($('#tp').value),dueDate:state.date,status:'open',completed:false,createdAt:Date.now()});close();toast('کار اضافه شد');render()}
function show(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('show')}function close(){$('#modal').classList.remove('show')}$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')close()})
function go(t){state.tab=t;render()}function openSettings(){settings()}
async function settings(){show(`<h2>تنظیمات</h2><div class="stack"><button class="secondary" onclick="exportData()">📦 خروجی گرفتن از تمام داده‌ها</button><button class="secondary" onclick="document.querySelector('#modalImport').click()">📥 وارد کردن پشتیبان</button><input id="modalImport" type="file" accept=".json" style="display:none" onchange="importData(event)"><hr><div class="small">نسخه فعلی: V0.1 · Offline-first · IndexedDB</div><div class="small">داده‌ها به‌صورت محلی روی دستگاه ذخیره می‌شوند. برای نصب مانند اپ، در Safari گزینه Add to Home Screen را بزن.</div></div>`)}
async function exportData(){let stores=['days','tasks','habits','habitLogs','events','people','journal','categories','sources','transactions'],data={version:1,exportedAt:new Date().toISOString(),stores:{}};for(const s of stores)data.stores[s]=await all(s);let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='life-planner-backup-'+isoDate(new Date())+'.json';a.click();URL.revokeObjectURL(a.href);toast('فایل پشتیبان ساخته شد')}
async function importData(e){let f=e.target.files[0];if(!f)return;try{let data=JSON.parse(await f.text());for(const [s,rows] of Object.entries(data.stores||{}))for(const x of rows)await put(s,x);close();toast('پشتیبان وارد شد');render()}catch(err){toast('فایل پشتیبان معتبر نیست')}}
async function init(){await openDB();await seed();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render()}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',1800)}
init();
